### ISSUE TITLE
Plugin usage numbers invalid for Network-enabled plugins

### ISSUE THREAD

**Issue by adamfranco** [middlebury/wordpress-audit#5]
In the Plugins overview the numbers reported for "number of sites" aren't valid for plugins that are network-enabled and by definition used by all sites in a network. Instead, they seem to reflect just the sites that enabled them individually before they were network-enabled.

**Comment by imcbride** [comment]
This is a bit tricky. The number of sites is calculated by counting the array size of the related sites returned via the ORM. I don't want to add a relationship in the database for a plugin that's not actually enabled on a site because then we have to worry about cleaning up when plugins become network deactivated.

Would an asterisk next to the number of sites if the plugin is network activated in at least one installation resolve this issue?

**Comment by adamfranco** [comment]
A leading asterisk would probably do it since that would allow the sort order to put all of the network-enabled plugins in a group. :+1:

**Comment by imcbride** [comment]
The latest change gets us closer, but combines the total number of sites in the installation with the number of sites on which the plugin is activated, leading to a larger number of sites than is accurate. Leaving this open and will update later with a custom query that resolves.
